(lang dune 3.23)

(name a2a)

(generate_opam_files true)

(source
 (github GildedHonour/a2a))

(authors "Alex Maslakoff <author@example.com>")

(maintainers "Alex Maslakoff <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name a2a)
 (synopsis "SDK for A2A protocol")
 (description "SDK for A2A protocol")
 (depends ocaml)
 (tags
  ("a2a")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
